INTERNAL_GW_MEMORY_LIMIT: "125Mi"
PRIVATE_GW_MEMORY_LIMIT: "125Mi"
PUBLIC_GW_MEMORY_LIMIT: "125Mi"
EGRESS_GW_MEMORY_LIMIT: "64Mi"
INTERNAL_GW_CPU_LIMIT: "500m"
PRIVATE_GW_CPU_LIMIT: "250m"
PUBLIC_GW_CPU_LIMIT: "250m"
EGRESS_GW_CPU_LIMIT: "100m"
CPU_REQUEST: "50m"
REPLICAS: 1
HPA_ENABLED: false
HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT: 75
HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS: 60
HPA_SCALING_UP_PODS_PERIOD_SECONDS: 60
HPA_SCALING_UP_PODS_VALUE: 1
HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS: 300
HPA_SCALING_DOWN_PODS_PERIOD_SECONDS: 60
HPA_SCALING_DOWN_PODS_VALUE: 1
HPA_MIN_REPLICAS: 1
HPA_MAX_REPLICAS: 5
HPA_SCALING_UP_SELECT_POLICY: Max
HPA_SCALING_DOWN_SELECT_POLICY: Max
HPA_SCALING_UP_PERCENT_PERIOD_SECONDS: -1
HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS: -1