---
{{- if or (and (eq .Values.PAAS_PLATFORM "KUBERNETES") (ne (semver .Values.PAAS_VERSION | (semver "1.25").Compare) 1)) (and (eq .Values.PAAS_PLATFORM "OPENSHIFT") (ne (semver .Values.PAAS_VERSION | (semver "4.10").Compare) 1)) }} # k8s older than 1.25 or os older than 4.10 (both included)
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: '{{.Values.INTERNAL_SERVICE }}'
  labels:
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.INTERNAL_SERVICE }}'
  {{- if .Values.HPA_ENABLED }}
  minReplicas: {{ coalesce .Values.HPA_MIN_REPLICAS .Values.REPLICAS }}
  maxReplicas: {{ .Values.HPA_MAX_REPLICAS }}
  {{- else }}
  minReplicas: 1
  maxReplicas: 9999
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ int (divf (mulf (default 75 .Values.HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT) (include "to_millicores" .Values.INTERNAL_GW_CPU_LIMIT)) (include "to_millicores" .Values.CPU_REQUEST)) }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ default 0 .Values.HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_UP_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_UP_PERCENT_VALUE (ge (int .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_UP_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_UP_PODS_VALUE (ge (int .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS) 0) }}
        - type: Pods
          value: {{ .Values.HPA_SCALING_UP_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS }}
{{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ default 300 .Values.HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_DOWN_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_DOWN_PERCENT_VALUE (ge (int .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_DOWN_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_DOWN_PODS_VALUE (ge (int .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS) 0)}}
        - type: Pods
          value: {{ .Values.HPA_SCALING_DOWN_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS }}
{{- end }}

---
{{- if or (and (eq .Values.PAAS_PLATFORM "KUBERNETES") (ne (semver .Values.PAAS_VERSION | (semver "1.25").Compare) 1)) (and (eq .Values.PAAS_PLATFORM "OPENSHIFT") (ne (semver .Values.PAAS_VERSION | (semver "4.10").Compare) 1)) }} # k8s older than 1.25 or os older than 4.10 (both included)
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: '{{.Values.PUBLIC_SERVICE }}'
  labels:
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.PUBLIC_SERVICE }}'
  {{- if .Values.HPA_ENABLED }}
  minReplicas: {{ coalesce .Values.HPA_MIN_REPLICAS .Values.REPLICAS }}
  maxReplicas: {{ .Values.HPA_MAX_REPLICAS }}
  {{- else }}
  minReplicas: 1
  maxReplicas: 9999
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ int (divf (mulf (default 75 .Values.HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT) (include "to_millicores" .Values.PUBLIC_GW_CPU_LIMIT)) (include "to_millicores" .Values.CPU_REQUEST)) }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ default 0 .Values.HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_UP_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_UP_PERCENT_VALUE (ge (int .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_UP_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_UP_PODS_VALUE (ge (int .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS) 0) }}
        - type: Pods
          value: {{ .Values.HPA_SCALING_UP_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS }}
{{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ default 300 .Values.HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_DOWN_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_DOWN_PERCENT_VALUE (ge (int .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_DOWN_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_DOWN_PODS_VALUE (ge (int .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS) 0)}}
        - type: Pods
          value: {{ .Values.HPA_SCALING_DOWN_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS }}
{{- end }}

---
{{- if or (and (eq .Values.PAAS_PLATFORM "KUBERNETES") (ne (semver .Values.PAAS_VERSION | (semver "1.25").Compare) 1)) (and (eq .Values.PAAS_PLATFORM "OPENSHIFT") (ne (semver .Values.PAAS_VERSION | (semver "4.10").Compare) 1)) }} # k8s older than 1.25 or os older than 4.10 (both included)
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: '{{.Values.PRIVATE_SERVICE }}'
  labels:
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{.Values.PRIVATE_SERVICE }}'
  {{- if .Values.HPA_ENABLED }}
  minReplicas: {{ coalesce .Values.HPA_MIN_REPLICAS .Values.REPLICAS }}
  maxReplicas: {{ .Values.HPA_MAX_REPLICAS }}
  {{- else }}
  minReplicas: 1
  maxReplicas: 9999
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ int (divf (mulf (default 75 .Values.HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT) (include "to_millicores" .Values.PRIVATE_GW_CPU_LIMIT)) (include "to_millicores" .Values.CPU_REQUEST)) }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ default 0 .Values.HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_UP_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_UP_PERCENT_VALUE (ge (int .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_UP_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_UP_PODS_VALUE (ge (int .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS) 0) }}
        - type: Pods
          value: {{ .Values.HPA_SCALING_UP_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_UP_PODS_PERIOD_SECONDS }}
{{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ default 300 .Values.HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS }}
      selectPolicy: {{ if .Values.HPA_ENABLED }}{{ default "Max" .Values.HPA_SCALING_DOWN_SELECT_POLICY }}{{ else }}Disabled{{ end }}
      policies:
{{- if and .Values.HPA_SCALING_DOWN_PERCENT_VALUE (ge (int .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS) 0) }}
        - type: Percent
          value: {{ .Values.HPA_SCALING_DOWN_PERCENT_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS }}
{{- end }}
{{- if and .Values.HPA_SCALING_DOWN_PODS_VALUE (ge (int .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS) 0)}}
        - type: Pods
          value: {{ .Values.HPA_SCALING_DOWN_PODS_VALUE }}
          periodSeconds: {{ .Values.HPA_SCALING_DOWN_PODS_PERIOD_SECONDS }}
{{- end }}